// Event payload types
export type {
  RoomCreatePayload,
  RoomJoinPayload,
  RoomLeavePayload,
  RoomCreatedPayload,
  RoomJoinedPayload,
  RoomLeftPayload,
  GameStartPayload,
  GamePausePayload,
  GameActionPayload,
  GameStartedPayload,
  GamePausedPayload,
  GameStateUpdatePayload,
  TokenMovePayload,
  TokenAddPayload,
  TokenRemovePayload,
  TokenMovedPayload,
  TokenAddedPayload,
  TokenRemovedPayload,
  DiceRollPayload,
  DiceResultPayload,
  ChatMessagePayload,
  ChatWhisperPayload,
  ChatMessageBroadcastPayload,
  ChatWhisperReceivedPayload,
  TurnEndPayload,
  TurnSkipPayload,
  TurnChangedPayload,
  TurnOrderUpdatedPayload,
  FogUpdatePayload,
  FogUpdatedPayload,
  NpcActionPayload,
  NpcActionBroadcastPayload,
  MapLoadPayload,
  MapUpdatePayload,
  MapLoadedPayload,
  MapUpdatedPayload,
  CharacterUpdatePayload,
  CharacterUpdatedPayload,
} from './event-types.js';

// Zod validation schemas
export {
  roomCreateSchema,
  roomJoinSchema,
  roomLeaveSchema,
  gameStartSchema,
  gamePauseSchema,
  gameActionSchema,
  tokenMoveSchema,
  tokenAddSchema,
  tokenRemoveSchema,
  diceRollSchema,
  chatMessageSchema,
  chatWhisperSchema,
  turnEndSchema,
  turnSkipSchema,
  fogUpdateSchema,
  npcActionSchema,
  mapLoadSchema,
  mapUpdateSchema,
  characterUpdateSchema,
} from './event-schemas.js';

// Typed Socket.IO event maps
export type { ClientToServerEvents } from './client-events.js';
export type { ServerToClientEvents } from './server-events.js';
